### ISSUE TITLE
Continuous integration with AppVeyor (Python 2.7 & 3.4 from python.org)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [vasily-v-ryabov/pywinauto-64#20]
I'm currently working on auto-install PowerShell script which downloads and installs Python from python.org, pyWin32 extensions, coverage 0.4 and Pillow 2.7 packages on clean Windows Server 2012.

**Comment by airelil** [comment]
You can take a look on my script for installing miniconda (all-in-one python packages) in my "testencoding" branch:
https://github.com/airelil/pywinauto-64/blob/test_encodings/ci/appveyor/install.ps1
BTW, when you get your AppVeyor machine several python versions are already installed in. I switched to miniconda because downloading and installation of pyWin32 was quite painful. On the other hand installing pywin32/Pillow/coverage from miniconda was just a breeze. If you prefer to use CI based on my "miniconda" approach just let me know so I can make a backport from my fork.

**Comment by airelil** [comment]
This is also the yml file:
https://github.com/airelil/pywinauto-64/blob/test_encodings/appveyor.yml
Notice about following params:
```yml
shallow_clone: true # enable fast clone without any history, just zip file of the current commit

os:
  - unstable # image with logged in user to allow a GUI interaction
```
